// Mock para canvas
export const createCanvas = jest.fn(() => ({
  width: 800,
  height: 600,
  getContext: jest.fn(() => ({
    fillStyle: '#000000',
    strokeStyle: '#000000',
    lineWidth: 1,
    font: '10px sans-serif',
    textAlign: 'start',
    textBaseline: 'alphabetic',
    globalAlpha: 1,
    globalCompositeOperation: 'source-over',
    save: jest.fn(),
    restore: jest.fn(),
    scale: jest.fn(),
    rotate: jest.fn(),
    translate: jest.fn(),
    transform: jest.fn(),
    setTransform: jest.fn(),
    resetTransform: jest.fn(),
    createLinearGradient: jest.fn(() => ({
      addColorStop: jest.fn(),
    })),
    createRadialGradient: jest.fn(() => ({
      addColorStop: jest.fn(),
    })),
    createPattern: jest.fn(),
    clearRect: jest.fn(),
    fillRect: jest.fn(),
    strokeRect: jest.fn(),
    beginPath: jest.fn(),
    closePath: jest.fn(),
    moveTo: jest.fn(),
    lineTo: jest.fn(),
    quadraticCurveTo: jest.fn(),
    bezierCurveTo: jest.fn(),
    arcTo: jest.fn(),
    arc: jest.fn(),
    rect: jest.fn(),
    fill: jest.fn(),
    stroke: jest.fn(),
    drawFocusIfNeeded: jest.fn(),
    clip: jest.fn(),
    isPointInPath: jest.fn(() => false),
    isPointInStroke: jest.fn(() => false),
    fillText: jest.fn(),
    strokeText: jest.fn(),
    measureText: jest.fn(() => ({
      width: 100,
      actualBoundingBoxLeft: 0,
      actualBoundingBoxRight: 100,
      actualBoundingBoxAscent: 10,
      actualBoundingBoxDescent: 2,
      fontBoundingBoxAscent: 12,
      fontBoundingBoxDescent: 3,
      emHeightAscent: 10,
      emHeightDescent: 2,
      hangingBaseline: 8,
      alphabeticBaseline: 0,
      ideographicBaseline: -2,
    })),
    drawImage: jest.fn(),
    createImageData: jest.fn(() => ({
      width: 100,
      height: 100,
      data: new Uint8ClampedArray(40000),
    })),
    getImageData: jest.fn(() => ({
      width: 100,
      height: 100,
      data: new Uint8ClampedArray(40000),
    })),
    putImageData: jest.fn(),
    setLineDash: jest.fn(),
    getLineDash: jest.fn(() => []),
    lineDashOffset: 0,
    shadowBlur: 0,
    shadowColor: 'rgba(0, 0, 0, 0)',
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    filter: 'none',
    imageSmoothingEnabled: true,
    imageSmoothingQuality: 'low',
    direction: 'ltr',
  })),
  toBuffer: jest.fn(() => Buffer.from('test-canvas')),
  toDataURL: jest.fn(() => 'data:image/png;base64,test'),
  toBlob: jest.fn(() => Promise.resolve(new Blob())),
  toFile: jest.fn(() => Promise.resolve({ name: 'test.png' })),
}));

export const createImageData = jest.fn(() => ({
  width: 100,
  height: 100,
  data: new Uint8ClampedArray(40000),
}));

export const loadImage = jest.fn(() => Promise.resolve({
  width: 100,
  height: 100,
  src: 'test-image.png',
}));

export const Image = jest.fn(() => ({
  width: 0,
  height: 0,
  src: '',
  onload: null,
  onerror: null,
  crossOrigin: null,
}));

export const Canvas = jest.fn(() => ({
  width: 800,
  height: 600,
  getContext: jest.fn(() => ({
    fillStyle: '#000000',
    strokeStyle: '#000000',
    lineWidth: 1,
    font: '10px sans-serif',
    textAlign: 'start',
    textBaseline: 'alphabetic',
    globalAlpha: 1,
    globalCompositeOperation: 'source-over',
    save: jest.fn(),
    restore: jest.fn(),
    scale: jest.fn(),
    rotate: jest.fn(),
    translate: jest.fn(),
    transform: jest.fn(),
    setTransform: jest.fn(),
    resetTransform: jest.fn(),
    createLinearGradient: jest.fn(() => ({
      addColorStop: jest.fn(),
    })),
    createRadialGradient: jest.fn(() => ({
      addColorStop: jest.fn(),
    })),
    createPattern: jest.fn(),
    clearRect: jest.fn(),
    fillRect: jest.fn(),
    strokeRect: jest.fn(),
    beginPath: jest.fn(),
    closePath: jest.fn(),
    moveTo: jest.fn(),
    lineTo: jest.fn(),
    quadraticCurveTo: jest.fn(),
    bezierCurveTo: jest.fn(),
    arcTo: jest.fn(),
    arc: jest.fn(),
    rect: jest.fn(),
    fill: jest.fn(),
    stroke: jest.fn(),
    drawFocusIfNeeded: jest.fn(),
    clip: jest.fn(),
    isPointInPath: jest.fn(() => false),
    isPointInStroke: jest.fn(() => false),
    fillText: jest.fn(),
    strokeText: jest.fn(),
    measureText: jest.fn(() => ({
      width: 100,
      actualBoundingBoxLeft: 0,
      actualBoundingBoxRight: 100,
      actualBoundingBoxAscent: 10,
      actualBoundingBoxDescent: 2,
      fontBoundingBoxAscent: 12,
      fontBoundingBoxDescent: 3,
      emHeightAscent: 10,
      emHeightDescent: 2,
      hangingBaseline: 8,
      alphabeticBaseline: 0,
      ideographicBaseline: -2,
    })),
    drawImage: jest.fn(),
    createImageData: jest.fn(() => ({
      width: 100,
      height: 100,
      data: new Uint8ClampedArray(40000),
    })),
    getImageData: jest.fn(() => ({
      width: 100,
      height: 100,
      data: new Uint8ClampedArray(40000),
    })),
    putImageData: jest.fn(),
    setLineDash: jest.fn(),
    getLineDash: jest.fn(() => []),
    lineDashOffset: 0,
    shadowBlur: 0,
    shadowColor: 'rgba(0, 0, 0, 0)',
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    filter: 'none',
    imageSmoothingEnabled: true,
    imageSmoothingQuality: 'low',
    direction: 'ltr',
  })),
  toBuffer: jest.fn(() => Buffer.from('test-canvas')),
  toDataURL: jest.fn(() => 'data:image/png;base64,test'),
  toBlob: jest.fn(() => Promise.resolve(new Blob())),
  toFile: jest.fn(() => Promise.resolve({ name: 'test.png' })),
}));

export default {
  createCanvas,
  createImageData,
  loadImage,
  Image,
  Canvas,
};
